export const NODE_COLUMNS = {
    // program
    File: '',
    Program: 'source_type TEXT',
    // statements
    BlockStatement: '',
    BreakStatement: '',
    ContinueStatement: '',
    DebuggerStatement: '',
    DoWhileStatement: '',
    EmptyStatement: '',
    ExpressionStatement: '',
    ForInStatement: '',
    ForOfStatement: 'is_await INTEGER',
    ForStatement: '',
    IfStatement: '',
    LabeledStatement: '',
    ReturnStatement: '',
    SwitchStatement: '',
    SwitchCase: '',
    ThrowStatement: '',
    TryStatement: '',
    CatchClause: '',
    WhileStatement: '',
    WithStatement: '',
    // declarations
    VariableDeclaration: 'kind TEXT',
    VariableDeclarator: '',
    FunctionDeclaration: 'generator INTEGER, async INTEGER',
    ClassDeclaration: '',
    // expressions
    ArrayExpression: '',
    ArrowFunctionExpression: 'generator INTEGER, async INTEGER',
    AssignmentExpression: 'operator TEXT',
    AwaitExpression: '',
    BinaryExpression: 'operator TEXT',
    CallExpression: '',
    ClassExpression: '',
    ConditionalExpression: '',
    FunctionExpression: 'generator INTEGER, async INTEGER',
    LogicalExpression: 'operator TEXT',
    MemberExpression: 'computed INTEGER',
    NewExpression: '',
    ObjectExpression: '',
    OptionalCallExpression: '',
    OptionalMemberExpression: 'computed INTEGER',
    ParenthesizedExpression: '',
    SequenceExpression: '',
    SpreadElement: '',
    Super: '',
    TaggedTemplateExpression: '',
    TemplateLiteral: '',
    ThisExpression: '',
    UnaryExpression: 'operator TEXT, prefix INTEGER',
    UpdateExpression: 'operator TEXT, prefix INTEGER',
    YieldExpression: 'delegate INTEGER',
    // patterns
    ArrayPattern: '',
    AssignmentPattern: '',
    ObjectPattern: '',
    RestElement: '',
    // classes
    ClassBody: '',
    ClassMethod: 'kind TEXT, static INTEGER, computed INTEGER, generator INTEGER, async INTEGER',
    ClassPrivateMethod: 'kind TEXT, static INTEGER, computed INTEGER, generator INTEGER, async INTEGER',
    ClassPrivateProperty: 'static INTEGER, computed INTEGER',
    ClassProperty: 'static INTEGER, computed INTEGER',
    PrivateName: '',
    // imports / exports
    ExportAllDeclaration: '',
    ExportDefaultDeclaration: '',
    ExportNamedDeclaration: '',
    ExportSpecifier: '',
    ImportDeclaration: 'source_value TEXT',
    ImportDefaultSpecifier: '',
    ImportNamespaceSpecifier: '',
    ImportSpecifier: '',
    // meta
    MetaProperty: '',
    // literals
    BigIntLiteral: 'value TEXT',
    BooleanLiteral: 'value INTEGER',
    DecimalLiteral: 'value TEXT',
    NullLiteral: '',
    NumericLiteral: 'value REAL',
    RegExpLiteral: 'pattern TEXT, flags TEXT',
    StringLiteral: 'value TEXT',
    TemplateElement: 'cooked TEXT, raw TEXT, tail INTEGER',
    DirectiveLiteral: 'value TEXT',
    InterpreterDirective: 'value TEXT',
    // JSX
    JSXAttribute: '',
    JSXClosingElement: '',
    JSXElement: '',
    JSXExpressionContainer: '',
    JSXFragment: '',
    JSXIdentifier: 'name TEXT',
    JSXMemberExpression: '',
    JSXNamespacedName: '',
    JSXOpeningElement: 'self_closing INTEGER',
    JSXOpeningFragment: '',
    JSXSpreadAttribute: '',
    JSXSpreadChild: '',
    JSXText: 'value TEXT',
    // misc
    CommentBlock: 'value TEXT',
    CommentLine: 'value TEXT',
    Identifier: 'name TEXT',
    ObjectProperty: 'computed INTEGER, method INTEGER, shorthand INTEGER',
    ObjectMethod: 'kind TEXT, computed INTEGER, generator INTEGER, async INTEGER',
    Placeholder: '',
    PipelineBareFunction: '',
    PipelinePrimaryTopicReference: '',
    PipelineTopicExpression: '',
    QualifiedTypeIdentifier: '',
    // TypeScript
    TSAnyKeyword: '',
    TSArrayType: '',
    TSAsExpression: '',
    TSBigIntKeyword: '',
    TSBooleanKeyword: '',
    TSCallSignatureDeclaration: '',
    TSConditionalType: '',
    TSConstructSignatureDeclaration: '',
    TSConstructorType: '',
    TSDeclareFunction: '',
    TSDeclareMethod: '',
    TSEnumDeclaration: '',
    TSEnumMember: '',
    TSExportAssignment: '',
    TSExpressionWithTypeArguments: '',
    TSExternalModuleReference: '',
    TSFunctionType: '',
    TSImportEqualsDeclaration: '',
    TSImportType: '',
    TSIndexSignature: '',
    TSIndexedAccessType: '',
    TSInferType: '',
    TSInterfaceBody: '',
    TSInterfaceDeclaration: '',
    TSIntersectionType: '',
    TSIntrinsicKeyword: '',
    TSLiteralType: '',
    TSMappedType: '',
    TSMethodSignature: '',
    TSModuleBlock: '',
    TSModuleDeclaration: '',
    TSNamedTupleMember: '',
    TSNamespaceExportDeclaration: '',
    TSNeverKeyword: '',
    TSNonNullExpression: '',
    TSNullKeyword: '',
    TSNumberKeyword: '',
    TSObjectKeyword: '',
    TSOptionalType: '',
    TSParameterProperty: '',
    TSParenthesizedType: '',
    TSPropertySignature: '',
    TSQualifiedName: '',
    TSRestType: '',
    TSSatisfiesExpression: '',
    TSStringKeyword: '',
    TSSymbolKeyword: '',
    TSTemplateLiteralType: '',
    TSThisType: '',
    TSTupleType: '',
    TSTypeAliasDeclaration: '',
    TSTypeAnnotation: '',
    TSTypeAssertion: '',
    TSTypeLiteral: '',
    TSTypeOperator: '',
    TSTypeParameter: '',
    TSTypeParameterDeclaration: '',
    TSTypeParameterInstantiation: '',
    TSTypePredicate: '',
    TSTypeQuery: '',
    TSTypeReference: '',
    TSUndefinedKeyword: '',
    TSUnionType: '',
    TSUnknownKeyword: '',
    TSVoidKeyword: '',
};
